Updated README to use the new install commands
sago35/tinygo-edit pull request #2
Opened 2022-08-26 15:36 UTC by headblockhead

Installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation

2022-08-27 04:18 UTC, sago35 requested changes
Thanks for the PR.
I think it is very good, but I have one comment.

2022-08-27 04:18 UTC, sago35 commented on README.md
> +export PATH="$HOME/go/bin/:$PATH"
Perhaps the following is correct

```suggestion
export PATH="$GOPATH/bin/:$PATH"
```

2022-08-27 09:32 UTC, headblockhead commented on README.md
> +export PATH="$HOME/go/bin/:$PATH"
Yes, thank you!

2022-09-02 08:16 UTC, headblockhead reviewed
I have added the changes requested.

2022-09-02 11:21 UTC, sago35 approved these changes
LGTM.
Thank you!

2022-09-02 11:22 UTC, sago35 commented
@headblockhead 
Now merging.

2022-09-02 11:22 UTC, merged